apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
spec:
  ...
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: reviews   
            routes:
            - primary                 # optional if there is a single route in VirtualService, required otherwise
          destinationRule:
            name: review-destination    # required
            canarySubsetName: v1  # required
            stableSubsetName: v2  # required
      steps:
      - setWeight: 90
      - pause:
          duration: 10m
